### ISSUE TITLE
high G force compensation during calculation of acceleration z value

### ISSUE THREAD

**Issue by ifrew** [har-in-air/ESP8266_MPU9250_MS5611_VARIO#1]
First off, kudos to you for a great  piece of work! I have this project now working with a mpu6050 gy-86 board too, using the DMP. I wanted to ask where in the code you compensate hi G, low G centripetal forces and whether it really make any difference? I couldn't see it. You made a reference to this in an older project the imu_kalman_altimeter PDF notes. Did you find that it doesn't really matter. Normally when you are thermaling your glider the g forces aren't that high going up.

".....However, the sensor can experience linear acceleration, centripetal forces, etc. in real-world applications.  So I’ve tweaked the AHRS reference code.  I added a flag to allow the AHRS algorithm to use the accelerometer data only when the acceleration vector magnitude is between 0.6g and 1.4g.  In low-g or high-g environments, the code discards the accelerometer data and just integrates the gyroscope rotation-rate data to update the orientation...."

**Comment by har-in-air** [comment]
Yes, I decided to use standard Mahony AHRS reference code as an experiment.   I think if you are in sustained acceleration/deceleration for a long time it's  a issue.  Abruptly switching in/out the acceleration input at a hard threshold could also introduce its own issues. So there is definitely a better solution to be found. Someone suggested using gps input as nowadays 5Hz/10Hz units are common.
I have not yet flown with the esp8266 vario (monsoon season here).  I have the feeling it will not be an problem, I am not an acro pilot :). 
Anyway, thanks for the input. Glad to hear it worked for you. The difference between a zero lag vario and a normal pressure based vario is startling at first !
If you put your project on github and give me a link that I could could reference in my readme file, that would be great, I already had someone asking me about using a MPU6050.
regardshari
 

    On Saturday, 16 September 2017 10:19 AM, ifrew <notifications@github.com> wrote:
 

 First off, kudos to you for a great piece of work! I have this project now working with a mpu6050 gy-86 board too, using the DMP. I wanted to ask where in the code you compensate hi G, low G centripetal forces and whether it really make any difference? I couldn't see it. You made a reference to this in an older project the imu_kalman_altimeter PDF notes. Did you find that it doesn't really matter. Normally when you are thermaling your glider the g forces aren't that high going up.".....However, the sensor can experience linear acceleration, centripetal forces, etc. in real-world applications. So I’ve tweaked the AHRS reference code. I added a flag to allow the AHRS algorithm to use the accelerometer data only when the acceleration vector magnitude is between 0.6g and 1.4g. In low-g or high-g environments, the code discards the accelerometer data and just integrates the gyroscope rotation-rate data to update the orientation...."—

**Comment by ifrew** [comment]
Thanks for quick reply! I haven't really used github at all other than to download zip files and use in Visual studio but once I've cleaned up the code I could. Forking, merging, updates, syncing is a bit of a pain! :-) At least to me, a hobbyist coder.

Wrt to the acceleration when turning, I didn't see how you compensated for it in your code, at least not in this project. I was wondering though, why wouldn't just taking the value of the acceleration in the z axis be sufficient rather than the magnitude of the acceleration since we are only interested in then vertical component anyway? And on that note I notice you use the following function to calculate the compensated gravity . I understand that you are using the quaternions to do the rotation but why are you just adding up the rotated values to get the acceleration compensated value.? If you wanted the magnitude wouldn't this be the sqrt(axax+ayay+azaz)? On my DMP implementation I am just using the value of the az vector after rotating and removing gravity, My thoughts being that is the only component we are interested in for vertical movement? Your thoughts? 

Cheers

Iain

float imu_GravityCompensatedAccel(float ax, float ay, float az, float q0, float q1, float q2, float q3) {
    float acc = 2.0*(q1*q3 - q0*q2)*ax + 2.0f*(q0*q1 + q2*q3)*ay +
        (q0*q0 - q1*q1 - q2*q2 + q3*q3)*az - 1.0f;
    acc *= 0.98f; // in cm/s/s, assuming ax, ay, az are in milli-Gs
	return acc;
    }

**Comment by har-in-air** [comment]
" but why are you just adding up the rotated values to get the acceleration compensated value.? If you wanted the magnitude wouldn't this be the sqrt(axax+ayay+azaz)? "

??? So you've read the pdf file from the kalmanfilter_altimeter_vario project then ?  Just selectively for trolling purposes ?  This isn't a twitter feed, it's a github project issues thread. If you want to contribute to the community, publish your project on github so other people can see and test an alternative implementation approach that uses the Invensense DMP.   That would be a productive use of your time.

**Comment by ifrew** [comment]
Not sure why you references trolling in the last comment. I was researching this on the internet trying to find out how to do this and came across your project. In any event, as I said GitHub all new to me, but I've pushed the project I have up now and I downloaded it and it seems to work fine. here is the link. Thanks again for your work on this! https://github.com/ifrew/esp32-vario

**Comment by romatou18** [comment]
![15839693839506599639471947970150](https://user-images.githubusercontent.com/60049000/76473578-c353b300-645d-11ea-9cd9-6bb6e6eeb774.jpg)
> Not sure why you references trolling in the last comment. I was researching this on the internet trying to find out how to do this and came across your project. In any event, as I said GitHub all new to me, but I've pushed the project I have up now and I downloaded it and it seems to work fine. here is the link. Thanks again for your work on this! https://github.com/ifrew/esp32-vario

Just getting an interest in altimetre and vario now as a hobbyist. The answer to why not using simply the az component alone and computing the vector norm sqrt(ax*ax+ay*ay+az*az) is certainly because the 3components x,y,z are all impacted by the gravity vector.

This is why when the DMP from the 9250 returns linear acceleration it is on 3components, and when returning the gravity vecor too. This is because if your imu frane is not aligned with the earth / world frame then the gravity vector wont be vertical following the z axis, but a x,y,z vector in the imu frame. 

Of course once all vectors you are looking at are translated in the earth/world frame you can co sider that thw gravity vector is exactly vertical and defines the z axis direction.

But until then, when measuring acceleration values from the accelerometer, you cannot assume that the az component represents the vertical acceleration . I.e. if your imu frame's z axis is 45 degrees left or right of the gravity vector, then the value of az will be a function of sin 45. 

Or if the imu is aligned differently from the normal orientation i.e. the y axis points down instead of the z axis, then the whole system will have to be rotated in the earth frame.

So the bottom line is the orientation is key, hence AHRS values to compute the gravity vector, the linear acceleration and the acceleration in the world frame. 

I'm not.an expert at all but this is what i understood from the papers I've read so far and the remains of my university education ;&)

The imu frame
